/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactUsRouteImport } from './routes/contact-us'
import { Route as OrderConfirmationRouteImport } from './routes/order-confirmation'
import { Route as PrivacyPolicyRouteImport } from './routes/privacy-policy'
import { Route as RefundAndCancellationPolicyRouteImport } from './routes/refund-and-cancellation-policy'
import { Route as ShippingPolicyRouteImport } from './routes/shipping-policy'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as TrackRouteImport } from './routes/track'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAccountRouteImport } from './routes/admin/account'
import { Route as AdminContentRouteImport } from './routes/admin/content'
import { Route as AdminIntegrationsRouteImport } from './routes/admin/integrations'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminTestimonialsRouteImport } from './routes/admin/testimonials'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiOrdersRouteImport } from './routes/api/orders'
import { Route as ApiTrackRouteImport } from './routes/api/track'
import { Route as ApiAdminContentRouteImport } from './routes/api/admin/content'
import { Route as ApiAdminInvoiceRouteImport } from './routes/api/admin/invoice'
import { Route as ApiAdminOrdersRouteImport } from './routes/api/admin/orders'
import { Route as ApiAdminProductsRouteImport } from './routes/api/admin/products'
import { Route as ApiAdminSettingsRouteImport } from './routes/api/admin/settings'
import { Route as ApiAdminStoreSettingsRouteImport } from './routes/api/admin/store-settings'
import { Route as ApiAdminTestimonialsRouteImport } from './routes/api/admin/testimonials'
import { Route as ApiPaymentCreateRouteImport } from './routes/api/payment/create'
import { Route as ApiPaymentVerifyRouteImport } from './routes/api/payment/verify'
import { Route as ApiWebhookRazorpayRouteImport } from './routes/api/webhook/razorpay'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsRoute = ContactUsRouteImport.update({
  id: '/contact-us',
  path: '/contact-us',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderConfirmationRoute = OrderConfirmationRouteImport.update({
  id: '/order-confirmation',
  path: '/order-confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyPolicyRoute = PrivacyPolicyRouteImport.update({
  id: '/privacy-policy',
  path: '/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundAndCancellationPolicyRoute =
  RefundAndCancellationPolicyRouteImport.update({
    id: '/refund-and-cancellation-policy',
    path: '/refund-and-cancellation-policy',
    getParentRoute: () => rootRouteImport,
  } as any)
const ShippingPolicyRoute = ShippingPolicyRouteImport.update({
  id: '/shipping-policy',
  path: '/shipping-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAccountRoute = AdminAccountRouteImport.update({
  id: '/admin/account',
  path: '/admin/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/admin/content',
  path: '/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/admin/integrations',
  path: '/admin/integrations',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/admin/testimonials',
  path: '/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiOrdersRoute = ApiOrdersRouteImport.update({
  id: '/api/orders',
  path: '/api/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrackRoute = ApiTrackRouteImport.update({
  id: '/api/track',
  path: '/api/track',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminContentRoute = ApiAdminContentRouteImport.update({
  id: '/api/admin/content',
  path: '/api/admin/content',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminInvoiceRoute = ApiAdminInvoiceRouteImport.update({
  id: '/api/admin/invoice',
  path: '/api/admin/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminOrdersRoute = ApiAdminOrdersRouteImport.update({
  id: '/api/admin/orders',
  path: '/api/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminProductsRoute = ApiAdminProductsRouteImport.update({
  id: '/api/admin/products',
  path: '/api/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSettingsRoute = ApiAdminSettingsRouteImport.update({
  id: '/api/admin/settings',
  path: '/api/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminStoreSettingsRoute = ApiAdminStoreSettingsRouteImport.update({
  id: '/api/admin/store-settings',
  path: '/api/admin/store-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminTestimonialsRoute = ApiAdminTestimonialsRouteImport.update({
  id: '/api/admin/testimonials',
  path: '/api/admin/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentCreateRoute = ApiPaymentCreateRouteImport.update({
  id: '/api/payment/create',
  path: '/api/payment/create',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentVerifyRoute = ApiPaymentVerifyRouteImport.update({
  id: '/api/payment/verify',
  path: '/api/payment/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhookRazorpayRoute = ApiWebhookRazorpayRouteImport.update({
  id: '/api/webhook/razorpay',
  path: '/api/webhook/razorpay',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation-policy': typeof RefundAndCancellationPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/track': typeof ApiTrackRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/invoice': typeof ApiAdminInvoiceRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/products': typeof ApiAdminProductsRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/store-settings': typeof ApiAdminStoreSettingsRoute
  '/api/admin/testimonials': typeof ApiAdminTestimonialsRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/webhook/razorpay': typeof ApiWebhookRazorpayRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation-policy': typeof RefundAndCancellationPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/track': typeof ApiTrackRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/invoice': typeof ApiAdminInvoiceRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/products': typeof ApiAdminProductsRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/store-settings': typeof ApiAdminStoreSettingsRoute
  '/api/admin/testimonials': typeof ApiAdminTestimonialsRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/webhook/razorpay': typeof ApiWebhookRazorpayRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/contact-us': typeof ContactUsRoute
  '/order-confirmation': typeof OrderConfirmationRoute
  '/privacy-policy': typeof PrivacyPolicyRoute
  '/refund-and-cancellation-policy': typeof RefundAndCancellationPolicyRoute
  '/shipping-policy': typeof ShippingPolicyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/track': typeof TrackRoute
  '/admin/account': typeof AdminAccountRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/integrations': typeof AdminIntegrationsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/api/config': typeof ApiConfigRoute
  '/api/orders': typeof ApiOrdersRoute
  '/api/track': typeof ApiTrackRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/content': typeof ApiAdminContentRoute
  '/api/admin/invoice': typeof ApiAdminInvoiceRoute
  '/api/admin/orders': typeof ApiAdminOrdersRoute
  '/api/admin/products': typeof ApiAdminProductsRoute
  '/api/admin/settings': typeof ApiAdminSettingsRoute
  '/api/admin/store-settings': typeof ApiAdminStoreSettingsRoute
  '/api/admin/testimonials': typeof ApiAdminTestimonialsRoute
  '/api/payment/create': typeof ApiPaymentCreateRoute
  '/api/payment/verify': typeof ApiPaymentVerifyRoute
  '/api/webhook/razorpay': typeof ApiWebhookRazorpayRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/contact-us'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/refund-and-cancellation-policy'
    | '/shipping-policy'
    | '/terms-and-conditions'
    | '/track'
    | '/admin/account'
    | '/admin/content'
    | '/admin/integrations'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/testimonials'
    | '/api/config'
    | '/api/orders'
    | '/api/track'
    | '/admin/'
    | '/api/admin/content'
    | '/api/admin/invoice'
    | '/api/admin/orders'
    | '/api/admin/products'
    | '/api/admin/settings'
    | '/api/admin/store-settings'
    | '/api/admin/testimonials'
    | '/api/payment/create'
    | '/api/payment/verify'
    | '/api/webhook/razorpay'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/contact-us'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/refund-and-cancellation-policy'
    | '/shipping-policy'
    | '/terms-and-conditions'
    | '/track'
    | '/admin/account'
    | '/admin/content'
    | '/admin/integrations'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/testimonials'
    | '/api/config'
    | '/api/orders'
    | '/api/track'
    | '/admin'
    | '/api/admin/content'
    | '/api/admin/invoice'
    | '/api/admin/orders'
    | '/api/admin/products'
    | '/api/admin/settings'
    | '/api/admin/store-settings'
    | '/api/admin/testimonials'
    | '/api/payment/create'
    | '/api/payment/verify'
    | '/api/webhook/razorpay'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/contact-us'
    | '/order-confirmation'
    | '/privacy-policy'
    | '/refund-and-cancellation-policy'
    | '/shipping-policy'
    | '/terms-and-conditions'
    | '/track'
    | '/admin/account'
    | '/admin/content'
    | '/admin/integrations'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/testimonials'
    | '/api/config'
    | '/api/orders'
    | '/api/track'
    | '/admin/'
    | '/api/admin/content'
    | '/api/admin/invoice'
    | '/api/admin/orders'
    | '/api/admin/products'
    | '/api/admin/settings'
    | '/api/admin/store-settings'
    | '/api/admin/testimonials'
    | '/api/payment/create'
    | '/api/payment/verify'
    | '/api/webhook/razorpay'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactUsRoute: typeof ContactUsRoute
  OrderConfirmationRoute: typeof OrderConfirmationRoute
  PrivacyPolicyRoute: typeof PrivacyPolicyRoute
  RefundAndCancellationPolicyRoute: typeof RefundAndCancellationPolicyRoute
  ShippingPolicyRoute: typeof ShippingPolicyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  TrackRoute: typeof TrackRoute
  AdminAccountRoute: typeof AdminAccountRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiOrdersRoute: typeof ApiOrdersRoute
  ApiTrackRoute: typeof ApiTrackRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiAdminContentRoute: typeof ApiAdminContentRoute
  ApiAdminInvoiceRoute: typeof ApiAdminInvoiceRoute
  ApiAdminOrdersRoute: typeof ApiAdminOrdersRoute
  ApiAdminProductsRoute: typeof ApiAdminProductsRoute
  ApiAdminSettingsRoute: typeof ApiAdminSettingsRoute
  ApiAdminStoreSettingsRoute: typeof ApiAdminStoreSettingsRoute
  ApiAdminTestimonialsRoute: typeof ApiAdminTestimonialsRoute
  ApiPaymentCreateRoute: typeof ApiPaymentCreateRoute
  ApiPaymentVerifyRoute: typeof ApiPaymentVerifyRoute
  ApiWebhookRazorpayRoute: typeof ApiWebhookRazorpayRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us': {
      id: '/contact-us'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order-confirmation': {
      id: '/order-confirmation'
      path: '/order-confirmation'
      fullPath: '/order-confirmation'
      preLoaderRoute: typeof OrderConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy-policy': {
      id: '/privacy-policy'
      path: '/privacy-policy'
      fullPath: '/privacy-policy'
      preLoaderRoute: typeof PrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund-and-cancellation-policy': {
      id: '/refund-and-cancellation-policy'
      path: '/refund-and-cancellation-policy'
      fullPath: '/refund-and-cancellation-policy'
      preLoaderRoute: typeof RefundAndCancellationPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping-policy': {
      id: '/shipping-policy'
      path: '/shipping-policy'
      fullPath: '/shipping-policy'
      preLoaderRoute: typeof ShippingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/account': {
      id: '/admin/account'
      path: '/admin/account'
      fullPath: '/admin/account'
      preLoaderRoute: typeof AdminAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/admin/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/integrations': {
      id: '/admin/integrations'
      path: '/admin/integrations'
      fullPath: '/admin/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/admin/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orders': {
      id: '/api/orders'
      path: '/api/orders'
      fullPath: '/api/orders'
      preLoaderRoute: typeof ApiOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/track': {
      id: '/api/track'
      path: '/api/track'
      fullPath: '/api/track'
      preLoaderRoute: typeof ApiTrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/content': {
      id: '/api/admin/content'
      path: '/api/admin/content'
      fullPath: '/api/admin/content'
      preLoaderRoute: typeof ApiAdminContentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/invoice': {
      id: '/api/admin/invoice'
      path: '/api/admin/invoice'
      fullPath: '/api/admin/invoice'
      preLoaderRoute: typeof ApiAdminInvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/orders': {
      id: '/api/admin/orders'
      path: '/api/admin/orders'
      fullPath: '/api/admin/orders'
      preLoaderRoute: typeof ApiAdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/products': {
      id: '/api/admin/products'
      path: '/api/admin/products'
      fullPath: '/api/admin/products'
      preLoaderRoute: typeof ApiAdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/settings': {
      id: '/api/admin/settings'
      path: '/api/admin/settings'
      fullPath: '/api/admin/settings'
      preLoaderRoute: typeof ApiAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/store-settings': {
      id: '/api/admin/store-settings'
      path: '/api/admin/store-settings'
      fullPath: '/api/admin/store-settings'
      preLoaderRoute: typeof ApiAdminStoreSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/testimonials': {
      id: '/api/admin/testimonials'
      path: '/api/admin/testimonials'
      fullPath: '/api/admin/testimonials'
      preLoaderRoute: typeof ApiAdminTestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/create': {
      id: '/api/payment/create'
      path: '/api/payment/create'
      fullPath: '/api/payment/create'
      preLoaderRoute: typeof ApiPaymentCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payment/verify': {
      id: '/api/payment/verify'
      path: '/api/payment/verify'
      fullPath: '/api/payment/verify'
      preLoaderRoute: typeof ApiPaymentVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhook/razorpay': {
      id: '/api/webhook/razorpay'
      path: '/api/webhook/razorpay'
      fullPath: '/api/webhook/razorpay'
      preLoaderRoute: typeof ApiWebhookRazorpayRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ContactUsRoute: ContactUsRoute,
  OrderConfirmationRoute: OrderConfirmationRoute,
  PrivacyPolicyRoute: PrivacyPolicyRoute,
  RefundAndCancellationPolicyRoute: RefundAndCancellationPolicyRoute,
  ShippingPolicyRoute: ShippingPolicyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  TrackRoute: TrackRoute,
  AdminAccountRoute: AdminAccountRoute,
  AdminContentRoute: AdminContentRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiOrdersRoute: ApiOrdersRoute,
  ApiTrackRoute: ApiTrackRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiAdminContentRoute: ApiAdminContentRoute,
  ApiAdminInvoiceRoute: ApiAdminInvoiceRoute,
  ApiAdminOrdersRoute: ApiAdminOrdersRoute,
  ApiAdminProductsRoute: ApiAdminProductsRoute,
  ApiAdminSettingsRoute: ApiAdminSettingsRoute,
  ApiAdminStoreSettingsRoute: ApiAdminStoreSettingsRoute,
  ApiAdminTestimonialsRoute: ApiAdminTestimonialsRoute,
  ApiPaymentCreateRoute: ApiPaymentCreateRoute,
  ApiPaymentVerifyRoute: ApiPaymentVerifyRoute,
  ApiWebhookRazorpayRoute: ApiWebhookRazorpayRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
